pipeline {
  agent {label 'docker-agents'}  
  
  stages {
    
    stage('Maven build') { 
           steps {
             build()
                 }
    }
    
     stage('Docker build') {
            steps {
              dockerBuild()
                  }
       
    }
      
        }
   
}
