pipeline {
    agent {label 'docker-agents'}  
     
stages {
    
    stage('CI') { 
           steps {
             Maven build
             Build docker image
             Docker deploy
           }
    }    
}   
}
